#!/bin/sh

# Copyright 2020 Ericsson Software Technology <viktor.soderqvist@est.tech>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

port=6661

printf '%s\n' 'SEND hello\r\n' 'RECV bye\r\n' 'CLOSE' \
    | timeout 5s perl ../mocksock.pl -p $port &
server=$!

printf '%s\n' 'RECV hello\r\n' 'SEND bye\r\n' 'PEER CLOSE' \
    | timeout 5s perl ../mocksock.pl -p $port -c &
client=$!

wait $server;
server_exit=$?

wait $client;
client_exit=$?

if [ $server_exit -ne 0 -o $client_exit -ne 0 ]
then
    echo "Server exit $server_exit, client exit $client_exit";
    exit 1;
fi
